[workspace]
members = [
  "git-ref-format",
  "git-trailers",
  "link-git",
  "radicle-git-ext",
  "radicle-git-types",
  "radicle-macros",
  "radicle-std-ext",
  # TODO: port gitd-lib over
  # "cli/gitd-lib",
  "test",
]
